version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo install completed on `date`
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - aws s3 cp s3://cmp-pipeline/build/broadleaf/codedeployscripts site/target --recursive
artifacts:
  files:
    - mycompany.war
    - appspec.yml
    - scripts/*
  discard-paths: no
  base-directory: site/target
 
