version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo install completed on `date`
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - echo "******** Uploading to S3 ********"
      - aws s3 cp site/target/mycompany.war s3://cmp-pipeline/build/broadleaf/
      - aws s3 cp broadleaf.json s3://cmp-pipeline/build/broadleaf/
artifacts:
  files:
    - site/target/mycompany.war
    - appspec.yml
    - scripts/*
  discard-paths: yes
